# Generated by Django 4.1 on 2022-08-31 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(default='营业收入', max_length=32, verbose_name='项目')),
                ('opening_balance', models.FloatField(max_length=32, verbose_name='期初余额')),
                ('debit_amount', models.FloatField(max_length=32, verbose_name='借方发生额')),
                ('credit_amount', models.FloatField(max_length=32, verbose_name='贷方发生额')),
                ('cumulative', models.FloatField(max_length=32, verbose_name='累计')),
            ],
            options={
                'verbose_name': '现金余额',
                'verbose_name_plural': '现金余额',
                'db_table': 'tb_cash_balance',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=32, verbose_name='序列号')),
                ('model', models.CharField(max_length=32, verbose_name='型号')),
                ('specifications', models.CharField(max_length=32, verbose_name='规格')),
                ('price', models.FloatField(default=0, verbose_name='单价')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'tb_goods',
            },
        ),
        migrations.CreateModel(
            name='GoodsBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='品牌')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品品牌',
                'verbose_name_plural': '产品品牌',
                'db_table': 'tb_goods_brand',
            },
        ),
        migrations.CreateModel(
            name='GoodsUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品单位',
                'verbose_name_plural': '产品单位',
                'db_table': 'tb_goods_unit',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32, verbose_name='小票编号')),
                ('customerName', models.CharField(max_length=32, null=True, verbose_name='客户名称')),
                ('handle_time', models.DateField(verbose_name='处理时间')),
                ('state', models.CharField(default='未付款未发货', max_length=32, verbose_name='小票状态')),
                ('total_amount', models.FloatField(null=True, verbose_name='销售总金额')),
            ],
            options={
                'verbose_name': '小票',
                'verbose_name_plural': '小票',
                'db_table': 'tb_receipt',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='手机号')),
                ('email', models.CharField(blank=True, max_length=256, null=True, verbose_name='邮箱')),
                ('sex', models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=32, verbose_name='性别')),
                ('roles', models.CharField(choices=[('sale', '销售'), ('cashier', '出纳'), ('goodsmanager', '库管')], max_length=32, verbose_name='性别')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='ReceiptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_quantity', models.FloatField(verbose_name='销售数量')),
                ('total_amount', models.FloatField(verbose_name='总金额')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales_goods_set', to='app.goods', verbose_name='产品')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_goods_set', to='app.receipt', verbose_name='小票')),
            ],
            options={
                'verbose_name': '小票明细',
                'verbose_name_plural': '小票明细',
                'db_table': 'tb_receipt_details',
            },
        ),
        migrations.AddField(
            model_name='receipt',
            name='consignor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales2_orders', to='app.user', verbose_name='发货人'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='drawer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales3_orders', to='app.user', verbose_name='发货人'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales1_orders', to='app.user', verbose_name='收款人'),
        ),
        migrations.CreateModel(
            name='GoodsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=32, verbose_name='货物盘点编号')),
                ('date', models.DateField(verbose_name='处理时间')),
                ('book_goods', models.FloatField(max_length=32, verbose_name='账面数量')),
                ('actual_goods', models.FloatField(max_length=32, verbose_name='实有数量')),
                ('Profit_loss', models.FloatField(max_length=32, verbose_name='盈亏')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='盈亏说明')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='goods_count', to='app.goods', verbose_name='产品')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goods_count', to='app.user', verbose_name='处理人')),
            ],
            options={
                'verbose_name': '现金盘点',
                'verbose_name_plural': '现金盘点',
                'db_table': 'tb_goods_count',
            },
        ),
        migrations.CreateModel(
            name='GoodsBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_quantity', models.FloatField(default=0, verbose_name='期初数量')),
                ('warehousing_quantity', models.FloatField(default=0, verbose_name='入库数量')),
                ('delivery_quantity', models.FloatField(default=0, verbose_name='出库数量')),
                ('total_quantity', models.FloatField(default=0, verbose_name='可用数量')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodbalances', to='app.goods', verbose_name='产品')),
            ],
            options={
                'verbose_name': '库存余额',
                'verbose_name_plural': '库存余额',
                'db_table': 'tb_goods_balance',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goods_set', to='app.goodsbrand', verbose_name='产品品牌'),
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goods_set', to='app.goodsunit', verbose_name='产品单位'),
        ),
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.CharField(max_length=32, verbose_name='现金盘点编号')),
                ('date', models.DateField(verbose_name='处理时间')),
                ('book_cash', models.FloatField(max_length=32, verbose_name='账面现金')),
                ('actual_cash', models.FloatField(max_length=32, verbose_name='实有现金')),
                ('Profit_loss', models.FloatField(max_length=32, verbose_name='盈亏')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='盈亏说明')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cash_count', to='app.user', verbose_name='处理人')),
            ],
            options={
                'verbose_name': '现金盘点',
                'verbose_name_plural': '现金盘点',
                'db_table': 'tb_cash_count',
            },
        ),
    ]
